// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace CommunityToolkit.Mvvm.SourceGenerators.UnitTests;

partial class Test_SourceGeneratorsCodegen
{
    private const string TestMessage = /* lang=c#-test */ """
public class TestMessage
{
    public string Content { get; set; } = string.Empty;
}
""";

    [TestMethod]
    public void IMessengerRegisterAll_GenerateCode()
    {
        string source = /* lang=c# */ $$"""
            using CommunityToolkit.Mvvm.Messaging;

            namespace MyApp;

            {{TestMessage}}

            public partial class MyViewModel : IRecipient<TestMessage>
            {
                public bool IsMessageReceived { get; private set; }
                public string ReceivedContent { get; private set; } = string.Empty;

                public void Receive(TestMessage message)
                {
                    IsMessageReceived = true;
                    ReceivedContent = message.Content;
                }
            }
            """;

        string result = /* lang=c# */ """
            // <auto-generated/>
            #pragma warning disable
            #nullable enable
            namespace CommunityToolkit.Mvvm.Messaging
            {
                /// <inheritdoc/>
                partial class __IMessengerExtensions
                {
                    /// <summary>
                    /// Registers all declared message handlers for a given <see cref="global::MyApp.MyViewModel"/> recipient, using the default channel.
                    /// </summary>
                    /// <inheritdoc cref="global::CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.RegisterAll(global::CommunityToolkit.Mvvm.Messaging.IMessenger,object)"/>
                    public static void RegisterAll(this global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, global::MyApp.MyViewModel recipient)
                    {
                        messenger.Register<global::MyApp.TestMessage>(recipient);
                    }

                    /// <summary>
                    /// Registers all declared message handlers for a given <see cref="global::MyApp.MyViewModel"/> recipient.
                    /// </summary>
                    /// <inheritdoc cref="global::CommunityToolkit.Mvvm.Messaging.IMessengerExtensions.RegisterAll{TToken}(global::CommunityToolkit.Mvvm.Messaging.IMessenger,object,TToken)"/>
                    public static void RegisterAll<TToken>(this global::CommunityToolkit.Mvvm.Messaging.IMessenger messenger, global::MyApp.MyViewModel recipient, TToken token)
                        where TToken : notnull, global::System.IEquatable<TToken>
                    {
                        messenger.Register<global::MyApp.TestMessage, TToken>(recipient, token);
                    }
                }
            }
            """;

        VerifyGenerateSources(source, new[] { new IMessengerRegisterAllGenerator() }, ("MyApp.MyViewModel.g.cs", result));
    }
}
